#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("generator.Resource", IsApplication=true)]

namespace generator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int LR1RadioButton = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int LR2RadioButton = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int LR3RadioButton = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int LR4RadioButton = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int LRGroup = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int Sub1RadioButton = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Sub2RadioButton = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Sub3RadioButton = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Sub4RadioButton = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int TDayOfIncludeTextView = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int TLastNameTextView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int TNumberTextView = 2131034113;
			
			// aapt resource value: 0x7f050018
			public const int februaryRadioButton = 2131034136;
			
			// aapt resource value: 0x7f05001d
			public const int lastnameEditText = 2131034141;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout1 = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int linearLayout2 = 2131034134;
			
			// aapt resource value: 0x7f05001a
			public const int linearLayout3 = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int mounthRadioGroup = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int numberText = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int resultVariantTextView = 2131034128;
			
			// aapt resource value: 0x7f05001f
			public const int saveButton = 2131034143;
			
			// aapt resource value: 0x7f050019
			public const int septemberRadioButton = 2131034137;
			
			// aapt resource value: 0x7f05001e
			public const int space1 = 2131034142;
			
			// aapt resource value: 0x7f050005
			public const int subjectGroup = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int textView1 = 2131034130;
			
			// aapt resource value: 0x7f050003
			public const int textView10 = 2131034115;
			
			// aapt resource value: 0x7f050013
			public const int textView2 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int textView3 = 2131034133;
			
			// aapt resource value: 0x7f05001b
			public const int textView4 = 2131034139;
			
			// aapt resource value: 0x7f05000a
			public const int textView5 = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int textView6 = 2131034116;
			
			// aapt resource value: 0x7f05001c
			public const int yearText = 2131034140;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Settings = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int DayNumber = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int Error = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Februar = 2130968586;
			
			// aapt resource value: 0x7f040018
			public const int Generate = 2130968600;
			
			// aapt resource value: 0x7f040014
			public const int LR1 = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int LR2 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int LR3 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int LR4 = 2130968599;
			
			// aapt resource value: 0x7f040006
			public const int LastName = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int MounthInclude = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int NumberInList = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int NumberLabWork = 2130968581;
			
			// aapt resource value: 0x7f040019
			public const int Save = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int Saved = 2130968602;
			
			// aapt resource value: 0x7f04000b
			public const int September = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int Subject = 2130968583;
			
			// aapt resource value: 0x7f040010
			public const int Subject1 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int Subject2 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int Subject3 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int Subject4 = 2130968595;
			
			// aapt resource value: 0x7f04000f
			public const int TCorrect = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int TDayOfInclude = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int TLastName = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int TNumber = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int Variant = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int YearInclude = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
